# Generated by Django 4.2.21 on 2025-06-14 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('ID_Product', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField()),
                ('product_category_name', models.CharField(max_length=225)),
                ('product_name_lenght', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_description_lenght', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProductShape',
            fields=[
                ('ID_Shape', models.AutoField(primary_key=True, serialize=False)),
                ('product_length_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_width_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_height_cm', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('ID_Shipping', models.AutoField(primary_key=True, serialize=False)),
                ('Shipping_Cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ID_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productcategory')),
                ('ID_Shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productshape')),
            ],
        ),
    ]
