# Generated by Django 4.2.21 on 2025-06-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_description_lenght',
            new_name='product_description_length',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_name_lenght',
            new_name='product_name_length',
        ),
    ]
