# Generated by Django 4.2.21 on 2025-06-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_product_description_lenght_productcategory_product_description_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='ID_Product',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product_category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product_description_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product_name_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
