# Generated by Django 4.2.21 on 2025-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_productcategory_id_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcost',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
