# Generated by Django 4.2.21 on 2025-06-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_shippingcost_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcost',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
